### PR TITLE
Generate images for readme

### PR DESCRIPTION
**Pull request by Darkclainer**
It doesn't work as intended, but maybe somebody know how to fix this.

I made script that generates svg files and crop them. And it's works when I open image in browser! But when I try to include image in README.md it looks awful. I can not control it size, and worse - crop doesn't work. 
(look https://github.com/Darkclainer/marker/blob/generate_images_for_readme/assets/svg/showoff.svg)

I tried to convert this svg files to png, but not inkspace nor cairosvg don't read this files correctly. 

Your ideas?

Issue #18

### CODE REVIEW

**Comment by jnatalzia** [comment]
Looks like based on the description in https://github.com/cyucelen/marker/pull/26 that this PR is no longer needed. Can we close this?

**Comment by Darkclainer** [comment]
I more like approach in this PR, but if nobody know how to fix problems with svg - I don't mind.

**Comment by cyucelen** [comment]
Can you try [svgexport](https://github.com/shakiba/svgexport) 
```
svgexport email.svg output.png 0:0:640:18
```
Does the job but image quality looks bad, maybe we can do something about it.

**Comment by Darkclainer** [comment]
I have seen this library, but it is in js, so it will be another big requirement to start this script.

**Comment by cyucelen** [comment]
Yes, but it is the only one that reads our svg correctly :confused:
Maybe we should go with html->png of your PR.

**Comment by Darkclainer** [comment]
OK.

**Pull request closed without merging**
