### PR TITLE
Add script that generates images for readme

### PR DESCRIPTION
**Pull request by Darkclainer**
Script helps to generate clean images from examples for README.md

Second solution. This actually works, but somebody (who knows css) should clean template for more neat output.

Issue #18

### CODE REVIEW

**Comment by cyucelen** [comment]
Actually, these images looks awesome! :yum:
Maybe we can compress them a little after generation, because each of them is about 600KB right now.

**Comment by Darkclainer** [comment]
Thank you for noticing. 
I made compression automatically.

**Comment by Darkclainer** [comment]
I've just realized, that I made mistake in the post above. Now script generates compressed images without any extra actions.
You simply do:
`./generate`

**Comment by cyucelen** [comment]
Is it generating compressed images now?

**Comment by Darkclainer** [comment]
Yes, it does.

**Pull request merged**
